In [1]:
import numpy as np
import tensorflow as tf

# Intro

In [2]:
x_train = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
y_train = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype = float)

In [3]:
import random

In [4]:
#Trainable Variables 
w = tf.Variable(random.random(), trainable=True)
b = tf.Variable(random.random(), trainable=True)

In [5]:
# Loss function
def simple_loss(real_y, y_pred):
    return tf.abs(real_y - y_pred)

In [6]:
LEARNING_RATE = 0.01

In [7]:
def fit_data(real_x, real_y):
    with tf.GradientTape(persistent=True) as tape:
        # Make Prediction
        pred_y = w * real_x + b
        
        # Calculate Loss
        reg_loss = simple_loss(real_y, pred_y)
     
    # Calculate Gradients   
    w_gradient = tape.gradient(reg_loss, w)
    b_gradient = tape.gradient(reg_loss, b)
    
    # Update variables 
    w.assign_sub(w_gradient*LEARNING_RATE)
    b.assign_sub(b_gradient*LEARNING_RATE)

In [9]:
for _ in range(500):
    fit_data(x_train, y_train)
    
print(f"y = {w.numpy()}x + {b.numpy()}")

y = 1.920434594154358x + -1.0110756158828735


# Gradient Descent

In [ ]:
def train_step(images, labels):
    with tf.GradientTape as tape:
        logits = model(images, trainable=True)
        loss_value = loss_object(labels, logits)
        
    loss_history.append(loss_value.nump().mean())
    grads = tape.gradient(loss_value, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

# Gradient of simple Equation


In [10]:
w = tf.Variable([[1.0]])

In [11]:
with tf.GradientTape() as tape:
    loss = w*w

In [12]:
tape.gradient(loss, w)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

# Gradient of a complex equation

In [20]:
x = tf.ones((2, 2))
with tf.GradientTape() as t:
    t.watch(x)

In [21]:
y = tf.reduce_sum(x)
z = tf.square(y)

In [22]:
dz_dx = t.gradient(z,x)

# Gradients with persistence = True

this helps for the gradient to be reused

In [27]:
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y = x ** 2
    z = y ** 2
dz_dx = t.gradient(z, x)
dy_dx = t.gradient(y, x)
del t

In [28]:
dz_dx

<tf.Tensor: shape=(), dtype=float32, numpy=108.0>

In [29]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

# Higher order gradients / Nested Gradient Tapes


In [32]:
x = tf.Variable(1.0)

with tf.GradientTape() as tape_1:
    with tf.GradientTape() as tape_2:
        y = 2 * x * x * x * x
    dy_dx = tape_2.gradient(y, x)
d2y_dx2 = tape_1.gradient(dy_dx, x)

In [33]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [34]:
d2y_dx2

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>