In [47]:
import tensorflow as tf
import numpy as np

# Storing Variables and constants

Understanding TensorFlow

In [6]:
"""A TensorFlow Object"""
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
e = tf.matmul(c, d)
print(e)
print(e.numpy())

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
[[1. 3.]
 [3. 7.]]


In [7]:
type(e)

tensorflow.python.framework.ops.EagerTensor

In [9]:
x = tf.Variable("Hello", tf.string)

In [13]:
x

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello'>

In [15]:
y = tf.constant([1, 2, 3, 4, 5, 6])

In [16]:
y

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

To Inspect variables of a bui-in keras layer

In [20]:
model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape = (1,))])

In [22]:
model.variables

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.9614092]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

## tf.Variable

In [31]:
tf.Variable(initial_value=[1,2])

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>

In [33]:
tf.Variable([1, 2, 3, 4], dtype=tf.float32)

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

No shape variable

In [34]:
tf.Variable([1, 2, 3, 4], dtype=tf.float32, shape=tf.TensorShape(None))


<tf.Variable 'Variable:0' shape=<unknown> dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

Strings and complex numbers

In [35]:
tf.Variable("Rabbit", dtype=tf.string)


<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Rabbit'>

In [36]:
tf.Variable(4 + 3j, dtype=tf.complex64)


<tf.Variable 'Variable:0' shape=() dtype=complex64, numpy=(4+3j)>

## tf.constant

In [37]:
tf.constant([1, 2, 3, 4])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [38]:
tf.constant([[1, 2], [3, 4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [39]:
tf.constant('Text')

<tf.Tensor: shape=(), dtype=string, numpy=b'Text'>

In [40]:
tf.constant([1, 2, 3, 4, 5, 6], shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [41]:
tf.constant(1.2, shape=(6,6))

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[1.2, 1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2, 1.2]], dtype=float32)>

# Operations

## Add


In [42]:
tf.add([1, 2], [3, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

In [44]:
tf.reduce_sum([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [46]:
# Operator Overloading
tf.square(2) + tf.square(3)

<tf.Tensor: shape=(), dtype=int32, numpy=13>

## Square

In [43]:
tf.square(5)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

## Reshape

In [48]:
x = np.arange(0, 25)

In [49]:
x = tf.constant(x)

In [50]:
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [51]:
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [52]:
x = tf.reshape(x, (5, 5))

In [53]:
x

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

## Miscellanous

In [54]:
# cast tensor x to float
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [55]:
y = tf.constant(2, dtype=tf.float32)

## Multiply

In [57]:
result = tf.multiply(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>