In [1]:
import tensorflow as tf

# Evaluate tensors

tensors are evaluated as they are created in eager mode

In [3]:
x = 2
x_squared = tf.square(x)
print("hello, {}".format(x_squared))

hello, 4


# Broadcast values

Broadcasting means instead of adding one by one, it just adds at once.

In [4]:
a  = tf.constant([
    [1, 2],
    [3, 4]
])
tf.add(a, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

# Overload Operators

meaning it can perform default python operations on tensors

In [5]:
a = tf.constant([
    [1, 2],
    [3, 4]
])

a ** 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

# Numpy Compatiblity

Tensorflow is compatoble with numpy and viz versa

In [6]:
import numpy as np
a = tf.constant(5)
b=tf.constant(7)
np.multiply(a, b)

35

# Numpy Interopability

In [7]:
ndarray = np.ones([3, 3])
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
tensor = tf.multiply(ndarray, 3)
tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])>

In [9]:
tensor.numpy()

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])