# Graph Training

Graph training as it compares to Eager training

In [1]:
import tensorflow as tf

## Eager Mode

In [5]:
def f(x):
    if x>0:
        x = x **2
    return x

f(5)

25

## Graph Mode

- No If functions
- Parallel computing
- compilation


In [6]:
@tf.function
def f(x):
    def if_true():
        return x **2
    def if_false():
        return x
    
    x = tf.cond(tf.greater(x, 0), if_true, if_false)
    return x

f(2)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [7]:
@ tf.function
def add(a, b):
    return a+ b

add(4, 5)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [8]:
print(tf.autograph.to_code(add.python_function))

def tf__add(a, b):
    with ag__.FunctionScope('add', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        try:
            do_return = True
            retval_ = ag__.ld(a) + ag__.ld(b)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [11]:
display(tf.autograph.to_graph(add.python_function))

<function __main__.outer_factory.<locals>.inner_factory.<locals>.tf__add(a, b)>

## Graph mode with gradient tape

In [12]:
del(add)

In [13]:
@tf.function
def add(a, b):
    return a+b

In [14]:
v = tf.Variable(1.0)

In [16]:
with tf.GradientTape() as tape:
    result = add(v, 2.0)

tape.gradient(result, v).numpy()

1.0

## tf.function with Keras

In [18]:
class CustomModel(tf.keras.models.Model):
    @tf.function
    def call(self,input_data):
        if tf.reduce_mean(input_data) > 0:
            return input_data
        else:
            return input_data // 2

## FizzBuzz Game

In [27]:
def fizzbuzz(max_num):
    counter = 0
    for num in range(max_num):
        if num%3 == 0 and num%5 == 0:
            print("FizzBuzz")
        elif num%3 ==0:
            print('Fizz')
        elif num%5 == 0:
            print('Buzz')
        else:
            print(num)
        counter += 1
    return counter

In [28]:
x = fizzbuzz(10)

FizzBuzz
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz


In [29]:
@tf.function
def fizzbuzz(max_num):
    counter = 0
    for num in range(max_num):
        if num%3 == 0 and num%5 == 0:
            print("FizzBuzz")
        elif num%3 ==0:
            print('Fizz')
        elif num%5 == 0:
            print('Buzz')
        else:
            print(num)
        counter += 1
    return counter

In [30]:
fizzbuzz(10)

FizzBuzz
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [39]:
@tf.function
def f(x):
    print("Traced with ", x)
    tf.print("Executed with", x)

In [40]:
for i in range(9):
    f(x)

Traced with  10
Executed with 10
Executed with 10
Executed with 10
Executed with 10
Executed with 10
Executed with 10
Executed with 10
Executed with 10
Executed with 10


In [41]:
import tensorflow as tf

In [44]:
@tf.function
def FizzBuzz(num):
    
    for i in range(1, num+1):
        if i%3 == 0 and i%5 ==0:
            print("FizzBuzz")
        elif i%3 == 0:
            print("Fizz")
        elif i%5 ==0:
            print("Buss") 
        else:
            print(i)
            

    

In [45]:
FizzBuzz(21)

1
2
Fizz
4
Buss
Fizz
7
8
Fizz
Buss
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buss
Fizz


In [47]:
print(tf.autograph.to_code(FizzBuzz.python_function))

def tf__FizzBuzz(num):
    with ag__.FunctionScope('FizzBuzz', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:

        def get_state_3():
            return ()

        def set_state_3(block_vars):
            pass

        def loop_body(itr):
            i = itr

            def get_state_2():
                return ()

            def set_state_2(block_vars):
                pass

            def if_body_2():
                ag__.ld(print)('FizzBuzz')

            def else_body_2():

                def get_state_1():
                    return ()

                def set_state_1(block_vars):
                    pass

                def if_body_1():
                    ag__.ld(print)('Fizz')

                def else_body_1():

                    def get_state():
                        return ()

                    def set_state(block_vars):
                        pass

                    